# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:/juMPuYEVK3MXTbTZLGMYteGtKwp4B49L6M=,iv:0azfHy/o/XnPnLyzFcCiSisWPI/Y8nrH3+1p8TKGbXg=,tag:x9GmLGNTdpGvAleAFKIlFw==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BYESJ3DK+w5vT3Ure6u9H1aRoCcWmsNUPJT7r+EQEfNk3RdHLakdafVjkqayUJgfG4ZUb5gvBALuZG2JBw7eOw==,iv:NUysLVxmiCul9wWxPsEgm0dAhKZMpcHjQwWRweTn9Ek=,tag:HHOK9vnz1iZ6dp/mGTS6zw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdkxXcGJTQ2NacHpON3hx
        dFd6bzh5OHlUdThHR25ab2ZCNy9kb3cvV1RJCkwrWDVrbUtNUWRMOU53YTJtdWcy
        Mm1oN2Y1Z0NhekRRQXFhK0ZtVkFzc3MKLS0tIGU2OXJhUk1sc3FFQmpCUm1vekM0
        dlYvYlE4T3k2N09URUVMU2pmK3U1UjQKAvZ/gRljutXeo+jPW36af/EpgLhRvsSb
        qygWYpQ92ApOX5UfI6/2+sTPnbS0Q94SmByemevFyh+JIPVqcOZOww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-08-15T09:12:04Z"
  mac: ENC[AES256_GCM,data:i96V+1N1U8S+5n+sN858oa1lF8b0xkqIDfpjkLl/LXBXPxDHQLmVgAi0vw8x53DAoGb71Ssepwj5ekL2KxfBY/Hius60N5bzwoMVIXFMmMl3D2By4UfYBwfSUJTvsJTiIVSSiImpuO4fvgAI0EacSeafrM78fmNpsgyqvRrs+KY=,iv:T/NeFN+WZJfndjheyup9M22BbZWmKk10quYLyDifrGU=,tag:k/CkARSslKuzLKLcwso+Tw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
