# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:FSfgavGALshgxOVpf0DVTY1A6qoqg36e97A=,iv:jpCHtP+X/tKCuXOc+VMmRPL7JWUw4IoGDaL9eWb3rQ4=,tag:HdLcRX7CTQ27nREZBWRXbg==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Peu9LMXF6KyenzPaIRBeCZH+DiGn9OfRxQ3XaWo9Gwx6WETIHe2YRBhmeqMv//LboRINOrJLeTP71qneOgp/TA==,iv:EyyFTZwku4tZErE/ec4hKilDeSrOp5601VXSbXdNxEw=,tag:5x51530tmcQqV51ttoeEVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdkxXcGJTQ2NacHpON3hx
        dFd6bzh5OHlUdThHR25ab2ZCNy9kb3cvV1RJCkwrWDVrbUtNUWRMOU53YTJtdWcy
        Mm1oN2Y1Z0NhekRRQXFhK0ZtVkFzc3MKLS0tIGU2OXJhUk1sc3FFQmpCUm1vekM0
        dlYvYlE4T3k2N09URUVMU2pmK3U1UjQKAvZ/gRljutXeo+jPW36af/EpgLhRvsSb
        qygWYpQ92ApOX5UfI6/2+sTPnbS0Q94SmByemevFyh+JIPVqcOZOww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-08-15T10:04:40Z"
  mac: ENC[AES256_GCM,data:JPNU0NynZg9enEihI2pLDlojm5+7PgygNUhgxNwK19W5yVjPrFNhkJepgKW7XxNYG+W7lyqU77zFWNt+LkmOKwNsj9pm5jEjD1S/56FjBggIRaD3A2gCSRs41PNVJ8DZUFBJwnkBEh4zxzvVaX7Qwr0tIYEle1H/F1aE0mwBXXI=,iv:zpbhqEC5DpE5iCgch0bjToeq3xosvURMEzsWJcsnGBo=,tag:tw28In1mZW1afOmFy4p8MQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
