# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  SECRETS_DIR: "{{.ROOT_DIR}}/home-ops-secrets"
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  TALOS_DIR: "{{.ROOT_DIR}}/talos"
  TALOS_DIR_OUT: "{{.SECRETS_DIR}}/clusterconfig"
  TALOSCONFIG: "{{.SECRETS_DIR}}/clusterconfig/talsoconfig"

env:
  KUBECONFIG: "{{.SECRETS_DIR}}/../kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.SECRETS_DIR}}/../age.key"
  TALOSCONFIG: "{{.TALOSCONFIG}}"

includes:
  bootstrap: .taskfiles/bootstrap
  talos: .taskfiles/talos

tasks:
  default: task --list

  reconcile:
    desc: Force Flux to pull in changes from your Git repository
    cmd: flux --namespace flux-system reconcile kustomization flux-system --with-source
    preconditions:
      - test -f {{.KUBECONFIG}}
      - which flux
