# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-credentials
stringData:
  user: ENC[AES256_GCM,data:PtX2+eFF,iv:Ti3n0OyH/PJS3A+44e6y54SYQ0QCrujTkZm7/B4Bitk=,tag:UdpBTo/Kyth08ZyD2VXSBw==,type:str]
  password: ENC[AES256_GCM,data:oLT2mC+y+VlWkXxBKsqatupxEvJRDkCPFnpn/jrN02hooc8yWyzJwxH9pFUtuQ==,iv:JSbNV8l4xsiekDcnaydxrYVP10tHYc3aWWD6aqsc46A=,tag:CSy3Ef0ZAvkwGYbEq+h2BQ==,type:str]
  network-key: ENC[AES256_GCM,data:/xS7AK1TQQFX1+4lfcHp1jQLQEw2WhEWR6JFI5vhbx6qQg30GyYoOM9muiZ3ejHlVaU+yQlsgEJ2uCIpojRliD1WDUuP9rJXMPjf//dOAYzNsgyyO3zM,iv:h4oZRo9ZR5rRNfehbouWMC2xVkQWa9uFc8B3Un/htFo=,tag:kh0b/jLJUHpiftUfC1Si6A==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZFlzWWFYYWxyWTNBU3FB
        V0xKUHJ4WTd0dlpDQnpEK0VFSzVXL2lTTEdjCncvb1htVDQwM0loL2prUkwzSzls
        L016Q1FsZ0hOS3ZmZi80eGZNUThDc3cKLS0tIFVlbkhPL29ueDRWQVAxK3hSZWpx
        QXl6T2lhQ1VCbFBjV3l3TnF6SjZTWTAKd7NWJyrOdJPBjzx0SHnvvBpL1EpRiey7
        1Iaq3+l851iGTcJMTn0qZBip8mg1SjLwZ7JTrwultnqdXdP6Ky8vKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-26T21:17:33Z"
  mac: ENC[AES256_GCM,data:91BPMUCRIknGR0JdsnrC83nTpK9GCaKAAF/7xicn6clIsFnF07ZQ0qqCEvwhohtQrV2Oc++7lWaAH9OzwTWWGkkSAvVl6IsEUHqGHQC8j+hzHbM2fRsm8O0aVQ0HsKd2+7O0VFAM+pPPrTqBInudlNKkfo39lxB0JKmtVOinhCQ=,iv:HZfuboyUnq06v8nQEIEJDoBIPqB0ULPhDiG3BzpAlk8=,tag:8xcxY8stU1keCSVurttkmQ==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  mac_only_encrypted: true
  version: 3.12.1
