# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-credentials
stringData:
  user: ENC[AES256_GCM,data:4qos5IGv,iv:3Y+zUfIMdXcpWV6kZ0VfpIUgTUaXJKj4GVEffEbM5v0=,tag:PBn77qD3yTP1NTActpFzXw==,type:str]
  password: ENC[AES256_GCM,data:uvmH/2g+ISPm0m/gnB1R0PvXJLqKvburuujc5TeGbpcwH0E/aKa2crE88PLreQ==,iv:WFhcficmFErbMBKZ3f5GHHEDwEh9GEC8YBCg4/JEs5o=,tag:x1zrFvt+G3sHkoE7tCmh9Q==,type:str]
  network-key: ENC[AES256_GCM,data:ccvCM/jVnGGvNbdt+Ib6qoHEDB0v03l/aaDo5cwU9BJoqJYGrIekDP8eW0xNOW4Vq58PMPp/6w6YkrlVl7vFQUuf/T3aRqrz4yCkmOq5glsfIvC1w1Zz,iv:ZZ4VObTrcN0yg0Jq1S9YoOkly2C6rIv3nUcNVuJk4eE=,tag:HmohO/Nsk1C/Wai+jvDeCg==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdWt1dU5ZZlNwTzQwNUUw
        R2NRZXQ3NVBQTW8wZk9zcVRkV25iREF1K244CldoTzM5QXVwdnlUSno5S0tZZ3o1
        T3A3cmJXZk1Dd29wTzlyT1VvOWoyVlEKLS0tIElaRk95d05INkVGeHNQdHpxRWk2
        YXpXa1V6N1BpeFVJUFRVZ1ZNM2hQSzQKsfAUocrk4M8UC+fyMxANwyLMXzR7dXsW
        +ItnN++01BzHoxeQFl6aQIvGqIPsqTTkgOlhEK/6HA/nEZu7Muretg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-26T20:57:09Z"
  mac: ENC[AES256_GCM,data:F/Pj15zFuY+uxTx7SKpM1NqkgvHZMVGMTWYUvmsu+wFs0DXS6mvBlJ0zYFbDIifs8IWwQy2ITBe9kOUKFR0YZD497jo1U6M9QG88jByyEQtJt7H/x67AFQq2C4HQ5eYI42gPmdzkCL5IclDHQgv1l+u3OTAZCz0gQG7eldBfXTY=,iv:nYjX87+nBTo4bNVSbMkDzhx52R3lyn8RhCZvRXOcJ/A=,tag:OdIWyCcV8o8OYb/fC6PfCw==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  mac_only_encrypted: true
  version: 3.12.1
