# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-credentials
stringData:
  user: ENC[AES256_GCM,data:KZGCBiJ4,iv:Hc4bMRiULIm+i4dOKfYBGPS+XX37VD+C5a6/TxzQBfo=,tag:mEkoAzim7Xv6T0Z/oeA+KQ==,type:str]
  password: ENC[AES256_GCM,data:s2/IHcmJXaZ8oOJ+u86htDTIFkGuJd3/CVzEzzrOds9gdbxTP7VJo5wQKuEfvw==,iv:UU0ox7j+aGJt+n/9GaRZvSHGX5Qn1Szv7NArTHluCJM=,tag:cMojsUKYxJbvp9cKShXGQA==,type:str]
  network-key: ENC[AES256_GCM,data:sKUw8fJ3bOu8UgD6WvMPKqeqdHtmL1I0D5Zsm9wfBUsKbtIcIyrTyH0OvdUX/imbM2ou/0QIu3D0Qw7pg4PvncF5MCCiCTY=,iv:tAKL9NkyOEsJkkMOtqX0XZMeSuuAZBGCOS3+1MWWfI8=,tag:bQ/n/jiWJLh9ACc53gM8AQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4emRhb1pva3h1QjdRNkVl
        bklLQUUwa1JXNWFzblptRlBuZW1HT05mSDJBCmpURmZjaHZlWjJRYy9RVmZ1WTZF
        QjFGbWZVaVErVFI5akkvVUhPeVBiS0EKLS0tIHB5VmVWeTY2aHg3TzRSdVhaejJL
        aitBMThjcERCa2VPZ0lWUXlxMVBNalUKsaJbbUwep+vHa2Hz5c/b37Wj9iZb/RCm
        dgXKYRYLneTRob771GgYcG5YGKd0IpZMcywb2hH1BvFqL1ZtddeIsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-26T21:11:03Z"
  mac: ENC[AES256_GCM,data:OpIgzLFOkaKag9SggfRCn/25gl4xVgtfdcZmUylmmiJZ9McFPTSKr9y6IkGSuTuK3aztfjj/UbVr+68NfEEt9urRZGjNa53pgJwrlOBk5B0hgQ2eOT+tk67/SLQSsI8zUx1XCFMUDXHm58bDAf3d6nkHzb/tYW66CMMKY+hTeJc=,iv:CZAZ0X34+wC28DGgOQQrweiH423jTF9rAo5HNPa44WA=,tag:anYWyOIOIP9Xxi/VUAQw1g==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  mac_only_encrypted: true
  version: 3.12.1
