# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-auth
stringData:
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:vku5f5QzVQnlTtN+vSPk17alHOvXp9JqmF1deE72pDu2mv6bfojXegEi+x3ps3X1/ixmbWNu2sxP/mK2IwKjeIo1f5gsWstTRTA=,iv:2be2FzxfB7pY4hAdfKfFdusGsN1R/XI+8wDwIPlOlts=,tag:jE79nVjGe6P7lb105NRgsA==,type:str]
#  NTFY_AUTH_ACCESS: ""
#  NTFY_AUTH_TOKENS: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU2tTbmlLRHpsSGhRak14
        K2RHTjhNV1RiUEtLcFVwTTIxV0lBZ3ZQeUQ4CktLVEw0SlZ4cUl0QktpWDNadjV3
        UHZRWjNiZlNUYnNNOXlVTDF4OEtCbVUKLS0tIE9abk44T2pJbGhHelZiMldKSzh2
        TCs3OGN1dDhqQ3FNdExURzZVTzJHSWMKwYgtd+9T7OyK9EFXawkUwZ+t/Hl3ZjQh
        q7quW414aq1b2Gskcz5Hdvwhyd7LoiJOz76VDIgT2SEBp4sJv4urqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-08-18T20:20:55Z"
  mac: ENC[AES256_GCM,data:i5YZtq1QZcSL7zJP/7HhvXRT3snOO+tzGCW5ctkLKOO9aOytLGVieWa9IKPVqAwoR8ngTbO3vULUE+RZ3FnUHtgF4ILKhJFP521mQ0IJhpX0bH7J8hVWSOXOY9JqWSVM2aFRMIqQ9HGLSfhjDYrwiwEby4tYoXVSNhXskR3WXC0=,iv:lQ9Sf25S2sHFqrxDz0hD0Li8wiCQdrblcGFfMiCWcOE=,tag:s+lLk2RtqLuGKcmj5dizAA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
