# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-auth
stringData:
  NTFY_AUTH_USERS: ENC[AES256_GCM,data:1HqVbxsbMu6MuC7pyjX3ZozVGkCgjkePdI1UOZktSn4ipX7lsTdRErgDqLy+joMxfKTbRltkPoHMiiDAuZRomRMH4p27gwftB5+M3Tibc5f5VS5GXziGyOWzaMNYEDJqxTnn1Gsx2zc13eG34mMQlO+2O2fi7Z3BUtAR7Ye7ryNbD6lkxECKR3EKwSpElzdUYkAx,iv:EHtGA7C9cQABfu44BPOHR+3zQndI3dJgK5s2DfASBwE=,tag:IMQ/0C2/zCpblZEIOoZrvQ==,type:str]
  NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:DbBIdXogl4onRC36VbLFew==,iv:BygaaP/4b3EFF+taCw9lLTXic2WXhrQJXXCrC+uyWmw=,tag:703Vb9x3xrUSMB6uB6HkxQ==,type:str]
  #ENC[AES256_GCM,data:YWbTDWAW0bx3Pvj5vSmy7dfDRt5HPWuqwed7,iv:yl0002sksJgDiuCNcpVa7+X0J9UYlFGtAuZZEQZSA0w=,tag:4y5M57JIymqSgXzZwjJYPQ==,type:comment]
  NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:AWK/QWbvLT32J6xF03D1d6hPBhfWGhTYtfd90kk03Gmd+bKj7bZnktH1B7NhzQM7ZH0TKTZ0oNQWpS67xUt8K2elKAX0170Og09Zzn3UXgoyORlawFwOpc7cbyy+xYJvJCZntam0rl7EfnD2hRdqA7urCWmHbBs=,iv:o+OXzwzBuBOqGmYZbHs5jig74fv9Q6acT3g2d1SCjdg=,tag:bKB/GU4CT+QiIx06cJScgg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU2tTbmlLRHpsSGhRak14
        K2RHTjhNV1RiUEtLcFVwTTIxV0lBZ3ZQeUQ4CktLVEw0SlZ4cUl0QktpWDNadjV3
        UHZRWjNiZlNUYnNNOXlVTDF4OEtCbVUKLS0tIE9abk44T2pJbGhHelZiMldKSzh2
        TCs3OGN1dDhqQ3FNdExURzZVTzJHSWMKwYgtd+9T7OyK9EFXawkUwZ+t/Hl3ZjQh
        q7quW414aq1b2Gskcz5Hdvwhyd7LoiJOz76VDIgT2SEBp4sJv4urqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-08-21T12:06:16Z"
  mac: ENC[AES256_GCM,data:fAbRBHC/+OU7iPlpCxethOjID67uduHcO3L4uA5I550IrM3AyabS8jt74pFn0nOH2MYLGzc/ssCiSh+A60hbkzwls6V7EmgVpoQQpbteyLGW5ueKFUm7r1gb/fqlhuoMZ4BwNmQTCrT/YcPcuDDzfcn2fPvEmBqeoAQaAAJ90Ig=,iv:JC6/3NHnqOvkn+jLDAnO1aF3V54Bdi7o3mwt/lRq9V0=,tag:BLcFEg9Xcm0sa/QI+HW39g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
