apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ntfy
spec:
  hostnames: ["ntfy.${SECRET_DOMAIN}"]
  parentRefs:
    - name: external
      namespace: network
  rules:
    - backendRefs:
        - name: ntfy
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
spec:
  type: ClusterIP
  selector:
    app: ntfy
  ports:
    - name: http-ntfy-out
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  labels:
    app: ntfy
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:v2.21.0@sha256:2b9e12d56a538f4402da51328eeca02696c4b207ab7fbe031c27e51a22ca9b86
          args: ["serve"]
          env:
            - name: NTFY_BASE_URL
              value: "https://ntfy.${SECRET_DOMAIN}"
            - name: NTFY_UPSTREAM_BASE_URL
              value: "https://ntfy.sh"
            - name: NTFY_LOG_LEVEL
              value: INFO
            - name: NTFY_CACHE-FILE
              value: "/var/cache/ntfy/cache.db"
            - name: NTFY_ATTACHMENT-CACHE-DIR
              value: "/var/cache/ntfy/attachments"
            - name: TZ
              value: Europe/Amsterdam
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 300Mi
              cpu: 200m
            requests:
              cpu: 150m
              memory: 150Mi
          volumeMounts:
            - mountPath: /var/cache/ntfy
              name: cache-volume
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: ntfy
