# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/daemonset-apps-v1.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      automountServiceAccountToken: false
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: generic-device-plugin
          image: squat/generic-device-plugin:latest@sha256:dc192e164c69b03f156765793a1be62ca437709ae477b27ca7d8f3dcf5021576
          args:
            - --domain=${SECRET_DOMAIN}
            - --device
            - |
              name: gpu
              groups:
                - count: 4
                  paths:
                    - path: /dev/kfd
                    - path: /dev/dri/renderD128
            - --device
            - |
              name: serial
              groups:
                - paths:
                    - path: /dev/ttyUSB*
                      optional: true
                - paths:
                    - path: /dev/ttyACM*
                      optional: true
          ports:
            - name: http-metrics
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
  updateStrategy:
    type: RollingUpdate
