{
 "title": "Garage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(block_bytes_read{job=\"garage-metrics\"}[$__rate_interval])    )",
     "legendFormat": "Disk bytes read"
    },
    {
     "expr": "-sum(rate(block_bytes_written{job=\"garage-metrics\"}[$__rate_interval])    )",
     "legendFormat": "Disk bytes written"
    }
   ]
  },
  {
   "title": "API requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (api_endpoint) (rate(api_s3_request_counter {job=\"garage-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{api_endpoint}}"
    }
   ]
  },
  {
   "title": "Web requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(web_request_counter {job=\"garage-metrics\"}[$__rate_interval]))",
     "legendFormat": "Web request rate"
    }
   ]
  },
  {
   "title": "RPC requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (rpc_endpoint) (rate(rpc_request_counter {job=\"garage-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{rpc_endpoint}}"
    }
   ]
  },
  {
   "title": "API errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (api_endpoint, status_code) (rate(api_s3_error_counter {job=\"garage-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{api_endpoint}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Web errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(web_error_counter {job=\"garage-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Resync queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "block_resync_queue_length{job=\"garage-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Table GC queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(table_name) (table_gc_todo_queue_length{job=\"garage-metrics\"})",
     "legendFormat": "{{ table_name}}"
    }
   ]
  },
  {
   "title": "Table Merkle updater queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum by(table_name) (table_merkle_updater_todo_queue_length{job=\"garage-metrics\"})",
     "legendFormat": "{{ table_name}}"
    }
   ]
  },
  {
   "title": "Resync errored blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "block_resync_errored_blocks{job=\"garage-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}