# yaml-language-server: $schema=https://json.schemastore.org/kustomization
resources:
  - dashboard.yaml
  - helmrelease.yaml
  - source.yaml
configMapGenerator:
  - name: garage-values
    behavior: create
    files:
      - values.yaml=values.yaml
    literals:
      - env-values.yaml=''
  - name: garage-dashboard
    behavior: create
    files:
      - dashboard.json=dashboard.json
configurations:
  - ../../utils/helm/kustomizeconfig.yaml
  - kustomizeconfig.yaml
