apiVersion: v1
kind: Service
metadata:
  name: prometheus-otel
spec:
  ports:
    - name: http-web
      port: 9090
      protocol: TCP
      targetPort: http-web
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-otel
