crds:
  installOtel: false
  installPrometheus: false
opentelemetry-operator:
  enabled: false
collectors:
  daemon:
    config:
      processors:
        transform/events:
          error_mode: ignore
          log_statements:
            - context: log
              statements:
                - set(resource.attributes["k8s.resource.type"], "events") where attributes["event.domain"] == "k8s"
      exporters:
        otlphttp/loki:
          endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
          headers:
            X-Scope-OrgID: platform
      service:
        pipelines:
          logs:
            processors:
              - k8s_attributes
              - resource_detection/env
              - resource/hostname
              - transform/events
              - batch
            exporters:
              - otlphttp/loki
