# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.6.2/charts/library/common/values.schema.json
defaultPodOptions:
  automountServiceAccountToken: false
  enableServiceLinks: false
  hostIPC: false
  hostNetwork: false
  hostPID: false
  shareProcessNamespace: false
  priorityClassName: platform-high
controllers:
  main:
    containers:
      main:
        image:
          repository: harbor.buijnsters.com/tgoo/dummy-backend
          tag: latest
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: cnpg-tgoo-app
                key: fqdn-jdbc-uri
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update
        resources:
          requests:
            cpu: 2000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 1Gi
service:
  main:
    ports:
      http:
        port: 8080
        protocol: TCP
route:
  main:
    parentRefs:
      - name: external
        namespace: network
    hostnames: ["tgoo-dummy.buijnsters.com"]
