# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netbird
  name: netbird
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: netbird
  template:
    metadata:
      labels:
        app: netbird
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - image: netbirdio/netbird:0.71.4-rootless@sha256:b41e7f4197e4e7fde09effc6722e182cc96b39625114e0830227d407670db607
          name: netbird
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
          envFrom:
            - secretRef:
                name: netbird-setup-key
          volumeMounts:
            - name: netbird-var
              mountPath: /var/lib/netbird
      volumes:
        - name: netbird-var
          persistentVolumeClaim:
            claimName: netbird-var
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbird-var
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: ssd-lvm-thin-2
  volumeMode: Filesystem
