# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netbird
  name: netbird
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: netbird
  template:
    metadata:
      labels:
        app: netbird
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - image: netbirdio/netbird:v0.74.7-rootless@sha256:dd545478026df785ce44e4b512fa11e5b0d1e7d94463c96a50675d72655050a0
          name: netbird
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              memory: 256Mi
          envFrom:
            - secretRef:
                name: netbird-setup-key
          volumeMounts:
            - name: netbird-var
              mountPath: /var/lib/netbird
      volumes:
        - name: netbird-var
          persistentVolumeClaim:
            claimName: netbird-var
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbird-var
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: ssd-lvm-thin-2
  volumeMode: Filesystem
