# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
stringData:
  NB_API_KEY: ENC[AES256_GCM,data:0Nl69ImARU/nZEK/aNmIlcOX9d3lcYF04Rmz0kMCfCkY0UmoFsnNoA==,iv:aZrUYqpyC2ZCFbDBooVXYjKi+W72KFeNAb3BhzGhDp4=,tag:vaSqM0ad7cqxEP+JCmbF6w==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUGVZWEZ6UDV0WGRRbWFO
        RW1vZjA1azlnanYzKzZxaG5LakJTcEcvdDNRCmp1RnI1TmZUTGZjR2RiN2pJaFJ2
        WFlKdHFPQU41VkFkbGlpS3JCSlRZSkUKLS0tIHk5REFNcVErdmI5dmFlOVllQ3VQ
        RjJBVmpHcjJuL3A3cmhwUFRjUWNUa2cKYHfomvEFOrqa+ikzB+ns76tOFisCzdIc
        1TNcr6tx4j07FXx851FrvbK8quFYJzCTRfTG0S8dvpynl10THKjwMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T22:13:48Z"
  mac: ENC[AES256_GCM,data:+mgSCxHwnybFggk0z8yBNhqj+YutC5vHMq2DpM1gkMP0+bee/2wtURGgyyKTUJC6qOlyp/D3XJh0Mr2oGr3z659G7Y91yadO9pXHxQcyMgqnYnRuihBPyoSGTsSPrf3K/b5cgUL+8BrMGM+om2lcyXo4ve7/OUsOQyEeOBC482g=,iv:S8oDGIhaydkZiEXUJzIDncBu0xG5kXE46GzrPSKJLZM=,tag:LFqotbdqbyzJ7jLJjHp9Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: netbird-setup-key
stringData:
  NB_SETUP_KEY: ENC[AES256_GCM,data:RlajFBDwS2Ji90JdwXwVhNBSMsK4oXd0KlDdDJJRg7QdlrFy,iv:yXpyd7pQHFz+4hAvZOBuhRPHQi3gexNx4Y0Yd9G/reQ=,tag:M0AMwjtSZdvtL2mQyPFtAQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUGVZWEZ6UDV0WGRRbWFO
        RW1vZjA1azlnanYzKzZxaG5LakJTcEcvdDNRCmp1RnI1TmZUTGZjR2RiN2pJaFJ2
        WFlKdHFPQU41VkFkbGlpS3JCSlRZSkUKLS0tIHk5REFNcVErdmI5dmFlOVllQ3VQ
        RjJBVmpHcjJuL3A3cmhwUFRjUWNUa2cKYHfomvEFOrqa+ikzB+ns76tOFisCzdIc
        1TNcr6tx4j07FXx851FrvbK8quFYJzCTRfTG0S8dvpynl10THKjwMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T22:13:48Z"
  mac: ENC[AES256_GCM,data:+mgSCxHwnybFggk0z8yBNhqj+YutC5vHMq2DpM1gkMP0+bee/2wtURGgyyKTUJC6qOlyp/D3XJh0Mr2oGr3z659G7Y91yadO9pXHxQcyMgqnYnRuihBPyoSGTsSPrf3K/b5cgUL+8BrMGM+om2lcyXo4ve7/OUsOQyEeOBC482g=,iv:S8oDGIhaydkZiEXUJzIDncBu0xG5kXE46GzrPSKJLZM=,tag:LFqotbdqbyzJ7jLJjHp9Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
