# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:s6zCcCqMgp8iavz1D71A+Jf3J94qEEjXc20Omisg2cU416+82wjK4Q==,iv:C7u5inrxkRWPMpQ+mnRwyRltfnjEuSpRrjogUxynhgg=,tag:Uz7QWfnOn+MyOySobK2AdQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZFg2UTJqSFFicmh6Rmlx
        UzcyTFB2alBhYmwyWDZXVk9zbGQwVjVSRWpvCjZoZnNZSlJSZXBRVGlIWFJLMi9q
        eTVrTVA2azZMeTNCSTJsc2t3N04wMVEKLS0tIDR0MWxSSGYrckNyanBZUHRERVZL
        UC9uZ3NmYWtDdFFUNTc4bFg3NlNTakUKxUAwkg2jq+0UyX8bZhF6xIlU8ESEy/cA
        0JWwPjTZhGxFQ7K9eRdrvMq2UqQ+vjcommuz0LhWkN3Ny2zorDkH/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T09:18:52Z"
  mac: ENC[AES256_GCM,data:KUqupRXgeE3pkkTsTye4k0WrTigb4iQyI96qtHwbHPx2AsbGSO1rPG6nogg+m/qZTxsN/eTAYpniu0Sq3B2HAHGeFmmhMlez7nJ/8L1VyV2oyI2NawMBQnXBgXgrEECAEOlRX7FKG3eE/7iPIvr/YC7cZRuW90Zf0mwYiNYnY7o=,iv:4/PQYHItxXGe6j8nuhSyQgEB/zKPrAn0Nqcf6xqxltA=,tag:Lp8FjxBLlYUs8uEaXl3j7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
