# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:xJtMibMyN6plErb/sBz9lwmeoaP95ou/SN2wHW4gT44=,iv:7E6NSm/sW/cMh5TmJeOiO06ZzvnSghSa/6gC28T6gC0=,tag:LYvc/D5ZON8godWHkFAGaA==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqazZyNFhLVmNiZkRpcGdk
        RE1GeFNubHFUR2dDb05oekxEUzFHQ0xaNnowClF2RVh6dmFTdkZPd2d6YnBnVC9O
        ejVYNW1JM3U3RkZ1WXVuT2FkZW04TUkKLS0tIFY2YTFqbytnejBYclBMK0pkbGFl
        MGFBUW1BQVU5UVBLSWNiaDZmdFhseWsKwU2rACbQVmy8k1urWrYQAYF/FtM4Tuvn
        PGifr+PVrAj+6qNq+rYv12wP4XpLRKzlE/xzBBPa6qVFPJpDB/twBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T09:18:53Z"
  mac: ENC[AES256_GCM,data:R+Fu4Ip3P6H5R5B4GKNPA3x8WiJfAKfjAPQXtVMn8ecS7sqVX1VtahPWR7JSrY7d7ynQ2X8NFww+zJzy/LQw2t4S+Tt/NlMP5P9JA017xLWX2PC5AM8py/ljkxHeZXHPb3Zm6uxMVe+oqpf41YtdDV0xQ9xV1YOYhQs8zB7ZsSM=,iv:LVZA98rxbCeHctYk/+vL0hIHOHeGzfeMgtNrAbnnVMs=,tag:CVERn2O9AYKwVDNLiryHGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
