# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - source.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: values-netbird-kubernetes-operator
    behavior: create
    files:
      - values.yaml=values-kubernetes-operator.yaml
    literals:
      - env-values.yaml=''
  - name: values-netbird-operator-config
    behavior: create
    files:
      - values.yaml=values-netbird-operator-config.yaml
    literals:
      - env-values.yaml=''
configurations:
  - ../../../utils/helm/kustomizeconfig.yaml
