# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
stringData:
  NB_API_KEY: ENC[AES256_GCM,data:pqSOtJTMf6LlyqjxZPqVChA29KBD05Ojn8XBF4VRfVa1L4kv5zIx7g==,iv:M9saXlnXJ01UdUxGOUXGB35N6+TNHERXVS6Ycq0u8jg=,tag:U54oOeDZo8v/GEin+mi6Jg==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUGVZWEZ6UDV0WGRRbWFO
        RW1vZjA1azlnanYzKzZxaG5LakJTcEcvdDNRCmp1RnI1TmZUTGZjR2RiN2pJaFJ2
        WFlKdHFPQU41VkFkbGlpS3JCSlRZSkUKLS0tIHk5REFNcVErdmI5dmFlOVllQ3VQ
        RjJBVmpHcjJuL3A3cmhwUFRjUWNUa2cKYHfomvEFOrqa+ikzB+ns76tOFisCzdIc
        1TNcr6tx4j07FXx851FrvbK8quFYJzCTRfTG0S8dvpynl10THKjwMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T20:24:56Z"
  mac: ENC[AES256_GCM,data:HCkVFxIMg3RQ3Ub7Ec+e6251RIw35ctSTEd3Y1NgQuIV5ixcvPz9Nv2nY5lFEfESyAbDIcxbjb/2L9H/4z9fFTEOzERcg5lrKpKUZP+sKpf6oGxU6X4Fi2ETwt4zWNfeRECsrLONLmZXh/ozyx/yg5UflJJqb7T8DzXW7NFUEak=,iv:pQ7xVkvr4FGlTcramR/PRK4fGIOeNPvqQ6tHE9HaH6o=,tag:bVAIXATx7x1DbnOpa+pmkA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
