# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
stringData:
  NB_API_KEY: ENC[AES256_GCM,data:gdsY4zz1LrkrN4YhzEm99MA+S1calKL52uDYcnv0ObWA5UqEoXPsqA==,iv:J0shKuunntzKuUs+yP1pd5CHUCNe38+iN/GEYHiqWDg=,tag:xsopn7nGg5gc7EJv8v8NwQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUGVZWEZ6UDV0WGRRbWFO
        RW1vZjA1azlnanYzKzZxaG5LakJTcEcvdDNRCmp1RnI1TmZUTGZjR2RiN2pJaFJ2
        WFlKdHFPQU41VkFkbGlpS3JCSlRZSkUKLS0tIHk5REFNcVErdmI5dmFlOVllQ3VQ
        RjJBVmpHcjJuL3A3cmhwUFRjUWNUa2cKYHfomvEFOrqa+ikzB+ns76tOFisCzdIc
        1TNcr6tx4j07FXx851FrvbK8quFYJzCTRfTG0S8dvpynl10THKjwMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T20:33:38Z"
  mac: ENC[AES256_GCM,data:hg35JbFKvKX7489QLKjVZHYgaUTMQPhAuDvmauXd54ssBVVkUos2xG0nTMk2Ik8phNaYpvi3VvgEObzBB+CAEIHCz63UNFm17T5Bq27ssXZLVwUfG91KDiOsaY/a43CMQWIwuh61d8NsqwGQLrtMDqFY5PECMgGc/2sIxsVH1GQ=,iv:14O5sujQNcTPKQzR+oAii4zxVrMyl8cfKHdp1NbINg8=,tag:8zndR+4eyNaH2/xdjh1gXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
