# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
stringData:
  NB_API_KEY: ENC[AES256_GCM,data:e65+erjos/yDdhUeGgbfJ9jHhOOPEwxVw2uVfNAPOYr1sbqerfkwdA==,iv:3VCqLHultUnwHxYBPG5nIdzGEVsjU88AE4cmxHumDak=,tag:U3MCLYGuQSOnfCAFmms0JA==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUGVZWEZ6UDV0WGRRbWFO
        RW1vZjA1azlnanYzKzZxaG5LakJTcEcvdDNRCmp1RnI1TmZUTGZjR2RiN2pJaFJ2
        WFlKdHFPQU41VkFkbGlpS3JCSlRZSkUKLS0tIHk5REFNcVErdmI5dmFlOVllQ3VQ
        RjJBVmpHcjJuL3A3cmhwUFRjUWNUa2cKYHfomvEFOrqa+ikzB+ns76tOFisCzdIc
        1TNcr6tx4j07FXx851FrvbK8quFYJzCTRfTG0S8dvpynl10THKjwMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T15:44:25Z"
  mac: ENC[AES256_GCM,data:K8+smzeAXni7tvXQ1p0QqACxGhsXyJhq/AcucLbtBOpfrbuG4MOr+WTa1mW69p1DNSyRIBicAgjXEVj9tz5EtV1pBLialUZdGZAObRoTXhkCSFxQO42ynGHphrPQtZy4PQsT0VMgs7VflA+S4uO94oqurara7pE9QpS9AP9S+5M=,iv:eNUK9VdJKuKOjaFEjWlSK96CUhUbZFFVRVRIe/598Ys=,tag:ZKg1TCvSvzkWQATLZfO97A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
