fullnameOverride: k8s-gateway
ttl: 1
priorityClassName: platform-critical
service:
  type: LoadBalancer
  port: 53
  annotations:
    lbipam.cilium.io/ips: "192.168.69.6"
  externalTrafficPolicy: Cluster
watchedResources: ["HTTPRoute", "Service"]
resources:
  requests:
    cpu: 10m
    memory: 40Mi
  limits:
    memory: 40Mi
