# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:stdJvvrn/D8UVgmvtzseCwrZtZNgClRLPefX0p9DQpZ8g4CyccvaeIbh0OudK07c15dJYIMCrPNyIv7fmBW4D4PhF+37Kmi4mRKKmhTgQhJYdn5RPpDsunoG9j4vNQkguTe02P5jUq5f36FceYCBaFObnkK8vKrd+FGxvBEXYMkeUhaK3bLZMGXXm7ocb9KTFG8DpAhOYn4T+9OVH457U+zDKQzP4rMP33eBNjUIqmVpMEVD,iv:G/gPoVrVtb6Im3CEsNCWkOiyeVbpI4gDWxl/4m/yDE0=,tag:FBnwB5+agU3lYWmlMvg35A==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNlo2eGdHZ3QxaFhPQ0sz
        bk5yM2tPUU4zRGsrYS80a05kRy9iUUNpQ1g4CmlMbHZhdTFTQk1pN0p3UWRBQ3Nu
        TGNUZ2lOSTEwOWQyOE9JMGI1UGpDYmMKLS0tIDVnWnRHcGNTd3BlcTR2MHVjR1hG
        ZlVUWHJURHhZR3QrSnlZZUQwZks4MzgKzLHDCWzjSorIr1YbAXkOBxIeE5n9KB/T
        rbG3QjUUQPI+4Esgu5w2PjJehFv2ILpFlFuS5A0fwCBUzFSl+y7KuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T09:18:52Z"
  mac: ENC[AES256_GCM,data:S/1l4s8KBXQyhznd9GAHjbTWnET0Xz9UoINwtBrnSgTshuyllEWBHHJi9h9dhHKqnLjHUB1WqXVWQZ7DHSfOSsT77ANJ/iP4PihXHY0bTIRFJ2q7oev7SckarJeokBOp0kfVVZxZSVWOOtlv+lseGsOHCPCxKO4LvbKz4xKsUtA=,iv:gM1ImwDL1TTHpDVWb649t11GJFkrwqczYDPF8BEFsxY=,tag:NEny2S5lCagBDWDlpMamtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
