provider:
  packages:
    - xpkg.upbound.io/crossplane-contrib/provider-sql:v0.9.0
resourcesCrossplane:
  requests:
    cpu: 50m
    memory: 512Mi
  limits:
    cpu: null
    memory: 512Mi
resourcesRBACManager:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: null
    memory: 50Mi
extraObjects:
  - apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    metadata:
      name: default
    spec:
      serviceAccountTemplate: {}
      deploymentTemplate:
        metadata: {}
        spec:
          selector: {}
          template:
            metadata: {}
            spec:
              containers:
                - name: package-runtime
                  resources:
                    requests:
                      cpu: 30m
                      memory: 256Mi
                    limits:
                      memory: 256Mi
