# https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: privileged-0
  labels:
    app: privileged
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: privileged
  template:
    metadata:
      labels:
        app: privileged
    spec:
      # nodeSelector:
      #   run-privileged: "true"
      containers:
        - image: ubuntu
          name: ubuntu
          resources: {}
          command:
            - "/bin/sh"
            - "-c"
            - "tail -f /dev/null"
          volumeMounts:
            - name: dev
              mountPath: /dev
            # - name: modules
            #   mountPath: /lib/modules
          securityContext:
            privileged: true
          # allowPrivilegeEscalation: false
          #   runAsNonRoot: true
          #   seccompProfile:
          #     type: RuntimeDefault
          #   capabilities:
          #     drop:
      volumes:
        - name: dev
          hostPath:
            path: /dev
        # - name: modules
        #   hostPath:
        #     path: /lib/modules
status: {}
