expose:
  tls:
    enabled: false
  type: route
  route:
    hosts:
      - harbor.buijnsters.com
    parentRefs:
      - name: internal
        namespace: network
externalURL: https://harbor.buijnsters.com
database:
  type: external
  external:
    host: cnpg-harbor-rw
    username: app
    existingSecret: cnpg-harbor-app
    coreDatabase: app
