apiVersion: v1
kind: Secret
metadata:
  name: kagent-ollama
type: Opaque
stringData:
  OLLAMA_API_KEY: ENC[AES256_GCM,data:WyRGyt6nx6E33TbwXFzv1YkKIKqOa5jE121k52jNd32X63YmRTHohzIovUuMFW2SMfxzU3qzIeU3nrlAvvsjmw==,iv:sBqBH0/KgKBSWSafbZ/Jf0jVKjteykLbdnHVySF2lRQ=,tag:N3Ni5BDSEXLZJbKkSJk9Pw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOWJQcERMTm5HRGpPTHI4
        WnllNEFvbFRUYUJtSVF4dWhkdGxKUVV6bVQ4CmNyK1UxcXhoeFR1SE5FdlEwaFRn
        dEVQNk1jZSswaFRIekhWd0ZnQzkxZWcKLS0tICtPSUt0V2dUendkcm9rZ2krbHo0
        dCtJUG01aFhTWVZSeVVMdmNmdk5ILzgKENppTtLvkHm4zpXvpN2Mg8wvqtHEeHug
        kIeqlE3Lstkc2gjn+h30rKeth0ugNcYaGzx38TBMPYjnsBVBojCk3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-10-04T19:08:33Z"
  mac: ENC[AES256_GCM,data:Aq6noct2OZxQjVlSvK6WsKl3vDrvkFESoT5bf8PMwfGcbA+DzS2WtMweXRNVq+CE4li2XmJYOecws3izhmcppQ7zrEW98amrgioWiIV5eueoyPZvPVQ5tLvlAapV/k0r4y/NU+/CyuGRGXVLtFbE+k1rUUy9FtGBGeO4zuhw0Rg=,iv:6Kb0dc385LO3D7WakTPyx9LPcVqZHUj2RyHb0+UJY2k=,tag:4rmUxs8tMzllri6cDRz5Kw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
