apiVersion: v1
kind: Secret
metadata:
  name: kagent-ollama
type: Opaque
stringData:
  API_KEY: ENC[AES256_GCM,data:bKflj7lrnhh0ndLW6r3eyf84K3dnlSmEl6yz67dqOZcdK9flcZJ62LZZ2l/63gprr3i5iLVleYpHN8ImvO1Czg==,iv:E9ilBXVN7/5BN2TD0vnm9oJAsHhX9X2aJ29qsZgderI=,tag:w5pBvrwLnWMK9eSh9ShTSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOWJQcERMTm5HRGpPTHI4
        WnllNEFvbFRUYUJtSVF4dWhkdGxKUVV6bVQ4CmNyK1UxcXhoeFR1SE5FdlEwaFRn
        dEVQNk1jZSswaFRIekhWd0ZnQzkxZWcKLS0tICtPSUt0V2dUendkcm9rZ2krbHo0
        dCtJUG01aFhTWVZSeVVMdmNmdk5ILzgKENppTtLvkHm4zpXvpN2Mg8wvqtHEeHug
        kIeqlE3Lstkc2gjn+h30rKeth0ugNcYaGzx38TBMPYjnsBVBojCk3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-10-04T18:56:30Z"
  mac: ENC[AES256_GCM,data:0jRdMSz7cNwwGa0vBh9nVy24m7X3Qa7bJPRBwyB3kRNdyYHx86FxEQYHdQ+CubOB/fIZhUNtakxM4a7ycsfTmdWqjinJODcJKHUtQ+NEPRaEBKDuynD+yqQAopE2bX4anhwINUt1Gfg/TyhQzYX8IlZjZASjjgaLMGgVyouxeGY=,iv:hvy67YpZ1SQqP5LP5wKqS3WrdDURA8TM53NSUUk1gKg=,tag:vyYIfa76Q6ex4DRbuTKdew==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
