apiVersion: v1
kind: Secret
metadata:
  name: kagent-ollama
type: Opaque
stringData:
  API_KEY: ENC[AES256_GCM,data:0YrOWyoe3MfIhVt+8oKsNVMpCQPD2gVdt5LSDzJ5DqH4C7PYaGqV+C5Gx3/jsull9VLqF19QyfZyUSkw/03tXQ==,iv:OLj+so6Rj52iSW8waqMa7SxtkiFu2TO2DaNH/fWtHf4=,tag:hqc79gsO2cOymIcIsL53Wg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOWJQcERMTm5HRGpPTHI4
        WnllNEFvbFRUYUJtSVF4dWhkdGxKUVV6bVQ4CmNyK1UxcXhoeFR1SE5FdlEwaFRn
        dEVQNk1jZSswaFRIekhWd0ZnQzkxZWcKLS0tICtPSUt0V2dUendkcm9rZ2krbHo0
        dCtJUG01aFhTWVZSeVVMdmNmdk5ILzgKENppTtLvkHm4zpXvpN2Mg8wvqtHEeHug
        kIeqlE3Lstkc2gjn+h30rKeth0ugNcYaGzx38TBMPYjnsBVBojCk3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-10-04T19:12:04Z"
  mac: ENC[AES256_GCM,data:4Xu9iMUo1lyMdjJPsWse0p/4hqe6Y7+YEMcLTHRh7RhCuS8+Ds2qWaskBY5LcFal+AA9SsBeD0sDS9zU8n6yFIxdKlS9BNcRMbzbRE1k1V1VCQ22xu7aOZQJHwcF+ddmDAY3aI17q9pQ0SDS2RAkOJS92gVRSb3pik1L2sPKu8U=,iv:MB81eisQNaK6eCkvm1nuv/8NyqguzyEGDpRszcbOf2w=,tag:FpVFIxXSSex8VfpfSTbTxg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
