controller:
  grpc:
    reflection: true
  substrate:
    ateApiEndpoint: dns:///api.ate-system.svc:443
    atenetRouterURL: http://atenet-router.ate-system.svc:80
    enabled: true
providers:
  default: ollama
  ollama:
    apiKeySecretRef: kagent-ollama
    apiKeySecretKey: API_KEY
    config:
      host: https://llm.buijnsters.com
substrateWorkerPool:
  create: true
  replicas: 1
  workerImage: ghcr.io/kagent-dev/substrate/ateom-gvisor:v0.3.0-alpha3
