controller:
  grpc:
    reflection: true
  substrate:
    ateApiEndpoint: dns:///api.ate-system.svc:443
    atenetRouterURL: http://atenet-router.ate-system.svc:80
    enabled: true
providers:
  default: openAI
  openAI:
    provider: OpenAI
    model: qwen3.8-flash-next
    apiKeySecretRef: kagent-ollama
    apiKeySecretKey: API_KEY
    config:
      baseUrl: https://llm.buijnsters.com/v1
substrateWorkerPool:
  create: true
  replicas: 1
  workerImage: ghcr.io/kagent-dev/substrate/ateom-gvisor:v0.3.0-alpha3
