# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:5afoLWnk9zWs+G07JGKTOUkR1cWonLMsgTS++wuKI3h8vdivMV15SA==,iv:dnJw00O+PSe7mXFTI5A9DjPUNsQKF3OVq7mj3mx900I=,tag:FHRxfbxFeX3fA2smsxI6sw==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwemVXRFIzWW9oZmZrOWxV
        MUJGRmVRL3k5MzhtUHplOFpuaXFjUkFIdjBRClVWQkRTbVdiRlhYTnhyVmVwd0lM
        eHNBRXF1RnA1UVhiSmppcE9BMnFUbDgKLS0tIDJ1WkFuWm1FekJvNWhSK2gxTWJY
        UUR1Z05OODZVRENJTVNXL3BnYjdrQ1EKaXx/AeVZpb5pAW4SFAgCZvWw0HdwxWAJ
        ynVBzjD3pZ2H+kc++bZyJcIqPqniYexQIFsYEsTwBeBH2ZBI4l/KOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-20T09:18:53Z"
  mac: ENC[AES256_GCM,data:anfMoakqjtrhNzA4nIN8riixOiJZogHTQmjmyRWQH3FAa0WDMC8BMK0hXv5Vyw8S2G/LvlWpXhvUoaOZFZPq4dOLCcNs/fAQRoesdwKAJ7t9JaUWLpqoPKMFrJHJfUUU0NdXPzy6pWpojsQpAgDO8mYaqbTTZ7IjDRVv5cJmwa0=,iv:upHtRTrDzvUlP7qzCmIBIPeqdy9iCk9yY3xC2zBlHZQ=,tag:85pEup5vprOFcugzDeDsqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
