# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: gpu-operator-charts
      version: v1.5.0
      sourceRef:
        kind: HelmRepository
        name: rocm
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: amd-gpu-operator-workflow-controller
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: amd-gpu-operator-workflow-controller
              spec:
                template:
                  spec:
                    containers:
                      - name: workflow-controller
                        resources:
                          requests:
                            cpu: 10m
                            memory: 90Mi
                          limits:
                            memory: 90Mi
  valuesFrom:
    - kind: ConfigMap
      name: values-amd-gpu-operator
    - kind: ConfigMap
      name: values-amd-gpu-operator
      valuesKey: env-values.yaml
