controllerManager:
  manager:
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 256Mi
kmm:
  controller:
    manager:
      resources:
        requests:
          cpu: 10m
          memory: 84Mi
        limits:
          memory: 84Mi
  webhookServer:
    webhookServer:
      resources:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          memory: 60Mi
node-feature-discovery:
  gc:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi
  master:
    resources:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
        memory: 80Mi
  worker:
    nodeSelector:
      kubernetes.io/arch: amd64
    resources:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
        memory: 80Mi
deviceConfig:
  spec:
    metricsExporter:
      resource:
        requests:
          cpu: 10m
          memory: 115Mi
        limits:
          memory: 115Mi
