apiVersion: v1alpha1
kind: LinkAliasConfig
name: ethSel0
selector:
  match: glob("e8:ff:1e:d2:90:ed", mac(link.hardware_addr))
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.69.5
link: ethSel0
---
apiVersion: v1alpha1
kind: LinkConfig
name: ethSel0
addresses:
  - address: 192.168.68.253/22
routes:
  - gateway: 192.168.68.1
