# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:RP3P6k1fQ7pPHxnCdVdLLliZJ+fgNgJUkn1u71qfAkfOfxjNzdUgfQ==,iv:6tzI5O2qVaIFS2Y8qaTdlOw2kILmBQd/C5JacZl2JG8=,tag:TArkttfS0psPPQkPVweIgQ==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqazZyNFhLVmNiZkRpcGdk
        RE1GeFNubHFUR2dDb05oekxEUzFHQ0xaNnowClF2RVh6dmFTdkZPd2d6YnBnVC9O
        ejVYNW1JM3U3RkZ1WXVuT2FkZW04TUkKLS0tIFY2YTFqbytnejBYclBMK0pkbGFl
        MGFBUW1BQVU5UVBLSWNiaDZmdFhseWsKwU2rACbQVmy8k1urWrYQAYF/FtM4Tuvn
        PGifr+PVrAj+6qNq+rYv12wP4XpLRKzlE/xzBBPa6qVFPJpDB/twBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T06:54:44Z"
  mac: ENC[AES256_GCM,data:yaENAUMu1GnaS3G91uILwlFPDYgHm0o0r6FIEE32siyFxcMP3CeZyDgJuF3YHI/k5Qu/V0ln0zy/WyCLQCTjr9Nt9bvq7zSxMDa3s8wdePNhIGAgpfQY0qxAGX1/sbtwlRtRHmkAxfdtrpkB4LKQ7O0Z2nxauazVBOL34n26Dy0=,iv:OpZNQ1NCvW33y57SXD75ZoCxTq+5MvQA327UgZtLGx0=,tag:1g4U6Ejq91y9dkthuJR5wQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
