instance:
  distribution:
    # renovate: datasource=github-releases depName=controlplaneio-fluxcd/distribution
    version: 2.8.8
  cluster:
    size: small
    networkPolicy: false
  components:
    - helm-controller
    - image-automation-controller
    - image-reflector-controller
    - kustomize-controller
    - notification-controller
    - source-controller
    - source-watcher
  sync:
    kind: GitRepository
    url: "https://github.com/Lingkar/home-ops.git"
    ref: "refs/heads/main"
    path: kubernetes/clusters/home
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux
  kustomize:
    patches:
      - # Set priorityClass of the flux components
        target:
          kind: Deployment
          name: (kustomize-controller|helm-controller|source-controller|source-watcher)
        patch: |
          - op: add
            path: /spec/template/spec/priorityClassName
            value: platform-high
      # Set resources
      - target:
          kind: Deployment
          name: helm-controller
        patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      requests:
                        cpu: 40m
                        memory: 512Mi
                      limits:
                        cpu: null
                        memory: 512Mi
      - target:
          kind: Deployment
          name: image-automation-controller
        patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      requests:
                        cpu: 20m
                        memory: 256Mi
                      limits:
                        cpu: null
                        memory: 256Mi
      - target:
          kind: Deployment
          name: image-reflector-controller
        patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      requests:
                        cpu: 20m
                        memory: 256Mi
                      limits:
                        cpu: null
                        memory: 256Mi
      - target:
          kind: Deployment
          name: kustomize-controller
        patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      requests:
                        cpu: 55m
                        memory: 300Mi
                      limits:
                        cpu: null
                        memory: 300Mi
      - target:
          kind: Deployment
          name: notification-controller
        patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      requests:
                        cpu: 10m
                        memory: 72Mi
                      limits:
                        cpu: null
                        memory: 72Mi
      - target:
          kind: Deployment
          name: source-controller
        patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      requests:
                        cpu: 20m
                        memory: 200Mi
                      limits:
                        cpu: null
                        memory: 200Mi
      - target:
          kind: Deployment
          name: source-watcher
        patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: all
          spec:
            template:
              spec:
                containers:
                  - name: manager
                    resources:
                      requests:
                        cpu: 10m
                        memory: 74Mi
                      limits:
                        cpu: null
                        memory: 74Mi
      - # Flux near OOM detection for Helm
        target:
          kind: Deployment
          name: helm-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --feature-gates=OOMWatch=true
