apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: admin
spec:
  forProvider:
    realmId: ENC[AES256_GCM,data:Gw0vRwGX,iv:Mzt7RauVDbpfzeG4FogffMsjnRswxlDfcoJDUOwtVPc=,tag:AonKON10W/5/EVQNG1bCZw==,type:str]
    firstName: ENC[AES256_GCM,data:XxLw,iv:+gWJDy4TRup6Fr17JurXbdoIC2XrwMwUXAbBqSM1cdo=,tag:e+SC9UXiE/YHBN9M7yotLA==,type:str]
    username: ENC[AES256_GCM,data:NUYJTQjfrdI=,iv:qln/+TlzsHb638M8klo3QVapcDvC/HkKbKLEFqwUtyU=,tag:H+iy+SYESYI3WqGvgSSl3g==,type:str]
    initialPassword:
      - temporary: ENC[AES256_GCM,data:FvTKCg==,iv:NlUmmyAFoWqnd5sjRyq6soU27pTFOh+R7G6awfSMWA8=,tag:z8ZvzgEwaO3djoQI3TYqQw==,type:bool]
        valueSecretRef:
          name: ENC[AES256_GCM,data:XFjWnu/s1oeHq5xifA==,iv:eTb1zhj6Z8LzxX+HEXOiPfNQDJxm8xAXUIEUrwF01vw=,tag:erBQaxyuGRexNoeCkuoszQ==,type:str]
          key: ENC[AES256_GCM,data:ca0FOtN8daEEn+4BHW/r,iv:HkzHnasSiRGSaZlcw7v3QScOcBOr1jFEoHH9f4QhOVc=,tag:Wg+xpDk/iVt5XBrWD6H9jQ==,type:str]
          namespace: ENC[AES256_GCM,data:LlO9G5kprkRppLHLbTKB,iv:VvkDj81vyolUUkucWTQhZ/R9Pqv5Pr85+dYEnt4vpzo=,tag:1KPSEP5ahYUUXhkaDOKyLQ==,type:str]
  providerConfigRef:
    name: ENC[AES256_GCM,data:v2IqTLf4BEsG01EVqmArkZxr,iv:H8wdxABGctU/CqfsZWo+jUeZoCtAlX7O2sNyyzP8T7Y=,tag:PA1qQ1uU42P5gdtiQDUyXw==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNGxmME11blh2Z1hhYkVP
        VmpNQXpWenFyRXhLTWFJVkg0VGtmekdhU21jCksrZnh2KzZKeHJtaU03YmxKbVNi
        MlZSbDN2Tjk0ejNRT2lhS2wrRDIyS2sKLS0tIExyT1p5a0c4RTFkSHE3Zi9WSmpD
        VnkwYzVZcU81L2dLUEd0bFBIRjQ3am8KTsRIwJCvcQ5rptOWBxNUmvuJ7IiwuRNX
        bRtTbLAzMJ1NCs6Prd9kD5nvlPveixXamRkV3PlGh8ZoynX33NidSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T19:28:01Z"
  mac: ENC[AES256_GCM,data:GbFuP2lgNtLsizlO9Mu7JmLBdkOASp2vgePx1BmtTE+Jeny3WDrzTVe5FyxRdXdoQdJKGhzODJrC/bcVCKwwfvw+dAmzQmR3hwHWiI0XnE3c4dh5Wi28TijyOTdXlLMyHLACrhRw6dqmikVUsMaaziWveMkoGUYZKK6YpEqF+k8=,iv:884P+254zf35RIP0eFiajTnBFKeARO2F/FtiMlIs5vk=,tag:U1/XXr8NfTfC8nint/9lpQ==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  mac_only_encrypted: true
  version: 3.12.2
