apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: admin
spec:
  forProvider:
    realmId: ENC[AES256_GCM,data:Gw0vRwGX,iv:Mzt7RauVDbpfzeG4FogffMsjnRswxlDfcoJDUOwtVPc=,tag:AonKON10W/5/EVQNG1bCZw==,type:str]
    firstName: ENC[AES256_GCM,data:XxLw,iv:+gWJDy4TRup6Fr17JurXbdoIC2XrwMwUXAbBqSM1cdo=,tag:e+SC9UXiE/YHBN9M7yotLA==,type:str]
    username: ENC[AES256_GCM,data:a1BR3RhpeA==,iv:cLf90C7S+CUbt1rERG19NO7sslaGc1J1zQ0p/dJHd3s=,tag:YgJDvHDO7AfPDSEpAmWlOw==,type:str]
    initialPassword:
      - temporary: ENC[AES256_GCM,data:F//4Ag==,iv:SfA0IpmFQkpU89/tXMGTA7hqzoYwE/vYKWrLjgWcemk=,tag:wwsnah7teJJIQ2VjmKckrA==,type:bool]
        valueSecretRef:
          name: ENC[AES256_GCM,data:71/GbocTrXESMGCzW0w=,iv:SWnZP+/J6QtOGVz9whvwI7gHcxFPfWqTnm8HJOSW0lY=,tag:Kt1n25k0hXSH7OMVPdQ09A==,type:str]
          key: ENC[AES256_GCM,data:ca0FOtN8daEEn+4BHW/r,iv:HkzHnasSiRGSaZlcw7v3QScOcBOr1jFEoHH9f4QhOVc=,tag:Wg+xpDk/iVt5XBrWD6H9jQ==,type:str]
          namespace: ENC[AES256_GCM,data:LlO9G5kprkRppLHLbTKB,iv:VvkDj81vyolUUkucWTQhZ/R9Pqv5Pr85+dYEnt4vpzo=,tag:1KPSEP5ahYUUXhkaDOKyLQ==,type:str]
  providerConfigRef:
    name: ENC[AES256_GCM,data:v2IqTLf4BEsG01EVqmArkZxr,iv:H8wdxABGctU/CqfsZWo+jUeZoCtAlX7O2sNyyzP8T7Y=,tag:PA1qQ1uU42P5gdtiQDUyXw==,type:str]
sops:
  age:
    - recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNGxmME11blh2Z1hhYkVP
        VmpNQXpWenFyRXhLTWFJVkg0VGtmekdhU21jCksrZnh2KzZKeHJtaU03YmxKbVNi
        MlZSbDN2Tjk0ejNRT2lhS2wrRDIyS2sKLS0tIExyT1p5a0c4RTFkSHE3Zi9WSmpD
        VnkwYzVZcU81L2dLUEd0bFBIRjQ3am8KTsRIwJCvcQ5rptOWBxNUmvuJ7IiwuRNX
        bRtTbLAzMJ1NCs6Prd9kD5nvlPveixXamRkV3PlGh8ZoynX33NidSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:07:45Z"
  mac: ENC[AES256_GCM,data:J0PXnxojDR2+Uw4LDqIxnfOJ71aArhk8XWgLJndFBX67TxGjc0j1kwvyZ+TA1mq9yKZX74Wh6JJWAHpQh3mj3cRVWmpTvUOTpi5bUcsQTL6++qMPD+40CsQMBpVcU7bgnEnUyapn6UcTYHLJlw9fCHmrZViAtj884ESqzbxwlK8=,iv:1lhX2iTPgdMr8Wvf1TqUErrGcTjYXqy87l7C6TVR3E8=,tag:iAbnhqU88IC9BIEYaW9vuQ==,type:str]
  encrypted_regex: ^(data|stringData|spec)$
  mac_only_encrypted: true
  version: 3.12.2
