# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-keycloak
spec:
  instances: 2
  storage:
    size: 1Gi
    storageClass: ssd-lvm-thin-1
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cnpg-keycloak
spec:
  name: app
  owner: app
  cluster:
    name: keycloak
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/k8s.keycloak.org/keycloak_v2alpha1.json
apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: kc-infra
spec:
  instances: 1
  db:
    vendor: postgres
    host: cnpg-keycloak-rw
    schema: app
    usernameSecret:
      name: cnpg-keycloak-app
      key: username
    passwordSecret:
      name: cnpg-keycloak-app
      key: password
  ingress:
    enabled: false
  hostname:
    hostname: keycloak.buijnsters.com
  http:
    tlsSecret: kc-server-cert
  proxy:
    headers: xforwarded
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cert-manager.io/issuer_v1.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
spec:
  dnsNames:
    - keycloak.buijnsters.com
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kc-server-cert
