apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: kc-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: kc-admin-creds
      key: credentials
      namespace: keycloak-system
---
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: infra
spec:
  forProvider:
    realm: infra
  providerConfigRef:
    name: kc-provider-config
---
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: KubernetesIdentityProvider
metadata:
  name: infra-kubernetes
spec:
  forProvider:
    realm: infra
    alias: kubernetes
    issuer: "https://192.168.69.5"
  providerConfigRef:
    name: kc-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: infra-admin
spec:
  forProvider:
    realmId: infra
    name: admin
  providerConfigRef:
    name: kc-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: infra-dev
spec:
  forProvider:
    realmId: infra
    name: dev
  providerConfigRef:
    name: kc-provider-config
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: infra-harbor
spec:
  forProvider:
    realmId: infra
    name: harbor
    clientId: harbor
    accessType: CONFIDENTIAL
    baseUrl: https://harbor.${SECRET_DOMAIN}
    rootUrl: https://harbor.${SECRET_DOMAIN}
    validRedirectUris:
      - https://harbor.${SECRET_DOMAIN}/*
  providerConfigRef:
    name: kc-provider-config
