# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-cloudflare-tunnel
spec:
  description: "Allow egress to cloudflare via DNS-aware FQDN policy"
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: cloudflare-tunnel
  egress:
    - toFQDNs:
        - matchName: region2.v2.argotunnel.com
    - toCIDR:
        - 192.168.69.8/32
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
