originRequest:
  matchSNItoHost: true

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://192.168.69.8
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - hostname: "phela-intelligence.com"
    service: *svc
  - hostname: "*.phela-intelligence.com"
    service: *svc
  - service: http_status:404
