# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.6.2/charts/library/common/values.schema.json
controllers:
  cloudflare-tunnel:
    strategy: RollingUpdate
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: docker.io/cloudflare/cloudflared
          tag: 2026.7.2@sha256:4f6655284ab3d252b7f28fedb19fe6c8fc82ee5b1295c20ac74d475e5398a52d
        env:
          NO_AUTOUPDATE: true
          TUNNEL_METRICS: 0.0.0.0:8080
          TUNNEL_ORIGIN_ENABLE_HTTP2: true
          TUNNEL_TRANSPORT_PROTOCOL: http2
        envFrom:
          - secretRef:
              name: cloudflare-tunnel-secret
        args: ["tunnel", "run"]
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ready
                port: &port 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 100m
            memory: 80Mi
          limits:
            memory: 80Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  priorityClassName: platform-critical
service:
  app:
    ports:
      http:
        port: *port
serviceMonitor:
  app:
    endpoints:
      - port: http
configMaps:
  cloudflare-tunnel-config:
    data:
      config.yaml: |-
        originRequest:
          originServerName: "external.${SECRET_DOMAIN}"
        ingress:
          - hostname: "${SECRET_DOMAIN}"
            service: &svc https://cilium-gateway-external.network.svc.cluster.local
          - hostname: "*.${SECRET_DOMAIN}"
            service: *svc
          - hostname: "phela-intelligence.com"
            service: *svc
          - hostname: "*.phela-intelligence.com"
            service: *svc
          - service: http_status:404
persistence:
  config-file:
    type: configMap
    identifier: cloudflare-tunnel-config
    globalMounts:
      - path: /etc/cloudflared/config.yaml
        subPath: config.yaml
        readOnly: true
