# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master-standalone/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
stringData:
  rootHost: ENC[AES256_GCM,data:wQ==,iv:UqOxED3s4pD/US96Voy5cPHBVhd8Bdq4iCQo0MXUse4=,tag:tAqZpZPFDHwbSNeBzW0BqA==,type:str]
  username: ENC[AES256_GCM,data:yhHHpA==,iv:0BZ7jPsLAmWPk2k7u3r/L7pHhk0TGA3ZUmdz33Cpx1U=,tag:eSbTHa2JwrKADcGQpWB8xg==,type:str]
  password: ENC[AES256_GCM,data:h+F8spmFfUMz+TrNR7ZpG+8KCg1QHJL4TIxbIngYMNsXq2lTt1wZWQVkJChmhA==,iv:QcDn0MB8zK3WPKwa7qfsnqCMCJOOFdiQJuj0SZIGUTk=,tag:kfBpAP4uBbkbgUPje3uMXw==,type:str]
  endpoint: ENC[AES256_GCM,data:dv/57mnisET3deSoAK5fh8/1+lyc8zgWAAuPwl1syg==,iv:JfnSax/8a5E9uph2ReBQG+grI2TG+z1AyAjr1oF65r8=,tag:5eZxgeyqsSt7WLp6BD5dFA==,type:str]
  port: ENC[AES256_GCM,data:lquSFw==,iv:2r8canQwluOa9ByLewjS//GtNq3Dm3pNtwf56/W0dRs=,tag:HJqUQfqjLaA/3frVFDnkxw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobjJyZHJkYmJtUFZLQTJw
        VU91WlZyRW1ZdHMyaGVKOWtJM29POFR5LzFBCksrZnRGbGRjTXIzMkZ1VHN5WnBy
        NzlPaVI0L0V4N2xLOXlOdGdCQzdaY3MKLS0tIHJNeFdRZnJwQzFhOWxaaVBTdTY1
        RDVxek5Jb1NHdGwxTVdVWE5oS2RTblUKMyaa1BBLjSU55b4OMn65dMHeBW8Hgxmx
        yd99eVk8OmEFAb+HUhJ/GQ6650BI1pqG84PMwNkL6oFPYIPCADa9qQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T23:19:15Z"
  mac: ENC[AES256_GCM,data:35kXeB4A/0UIgjdt7XlEh1rtLd08YhaCQ/pyxh1bIvjhz9kGJTmEIaCQwCWIirbQMyiuv80rfmhDBCuINtCC5iyoPMXbezxjmovtHi/nsGBXqw6HVnlAMkxTGn7jjJGirzUhS2DvjhnG0xExy2AdjsMFI5EhlWKMOvJuQlh50E4=,iv:tx0UNy/x+HUTKtqo7II4ChYqlgKeQvtEctRJS+6pqkU=,tag:Ye+jYB16fAOtR0XdPWwQKw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
