apiVersion: v1
kind: Secret
metadata:
  name: llm-api-key
type: Opaque
stringData:
  API_KEY: ENC[AES256_GCM,data:paUcmfSyNm3POP2J+Hl8KrV+MyX2IRh/gAHkZcggEDzAf0Zd1toY8gmEtW1ZHJCxS7H1GRPicAjWZ0T4aY1OUA==,iv:bj8b0xrkIcSuoPxfHwCOmwSpK13tRVvAgpZLVoUhg8I=,tag:K4jMfDUKO1W2CKj8NdFz5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdHkxUUU5QkhpYkxycFZx
        ekpEdUJzTmFBOVNWaEFxenJrZlRHbTZ4VWxvCjlaTndGdmhVNWRmdUlUSlZEOFZj
        LzJQbEl3UlMraWVKOWs2V1hXWlQ5Q1UKLS0tIGU2SWVoc1Q1SGdsRWFGK2hjaVZy
        eDViSVBSaWZlVVRYbS80c2hFN2hIV2MK8xLfE5S7bOAwWL6ApsyfN1Z0YlCklfIh
        lbgLRpB7WCSkIskdJlwtGIdlMGr7FLJa67+LA7NOT+3aOBdEc/K4gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10gr3hs4ug9z2mhzjxe9gcz5wh2vj9c2rlxzh93l0rkm7cap3rdvsecduzs
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-09-26T15:16:23Z"
  mac: ENC[AES256_GCM,data:soEKpV3Cb22dXIC48JVQ+y0CDNGblpV+cN/Hhbfc9W5kGYHcYa+qKDjIqty4ip8T5LzVkm+1o5F9TKXUM9+kbS624pmzvF3Fa6YUvGID5fbSD0Ou3sTGQzJ/t8fnNlu3+7IOAOVWhi4ZM1lINlGzJv7/Tjxe82jJSF+Gbw4I74Y=,iv:wKgFHvFm4kynsXSi48lETGEtj/8w51r4ommx4XZK/g4=,tag:7EYRpf6idR5z15i3VvLQzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
